USE [master]
GO

/****** Object:  Database [AlumnosCursos]    Script Date: 18/11/2016 08:32:45 ******/
CREATE DATABASE [AlumnosCursos] ON  PRIMARY 
( NAME = N'AlumnosCursos', FILENAME = N'D:\AlumnosCursos.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AlumnosCursos_log', FILENAME = N'D:\AlumnosCursos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AlumnosCursos] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AlumnosCursos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AlumnosCursos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AlumnosCursos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AlumnosCursos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AlumnosCursos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AlumnosCursos] SET ARITHABORT OFF 
GO

ALTER DATABASE [AlumnosCursos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AlumnosCursos] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AlumnosCursos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AlumnosCursos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AlumnosCursos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AlumnosCursos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AlumnosCursos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AlumnosCursos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AlumnosCursos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AlumnosCursos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AlumnosCursos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AlumnosCursos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AlumnosCursos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AlumnosCursos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AlumnosCursos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AlumnosCursos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AlumnosCursos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AlumnosCursos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AlumnosCursos] SET  READ_WRITE 
GO

ALTER DATABASE [AlumnosCursos] SET RECOVERY FULL 
GO

ALTER DATABASE [AlumnosCursos] SET  MULTI_USER 
GO

ALTER DATABASE [AlumnosCursos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AlumnosCursos] SET DB_CHAINING OFF 
GO

USE [AlumnosCursos]
GO

/****** Object:  Table [dbo].[Alumnos]    Script Date: 18/11/2016 08:33:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Alumnos](
	[Legajo_Alumno] [int] NOT NULL,
	[Apellido_Alumno] [varchar](50) NULL,
	[Curso_Alumno] [int] NULL,
 CONSTRAINT [PK_Alumnos] PRIMARY KEY CLUSTERED 
(
	[Legajo_Alumno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


